### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by jacerider** [marcj/angular2-localStorage#12]
Hello,

Trying to use this along with the angular2-seed project. They have pretty strict typescript settings and as a result of that there are compiling errors. The errors I am getting are as follows:

`TSError: ⨯ Unable to compile TypeScript
node_modules/angular2-localstorage/LocalStorageEmitter.ts (6,5): Member 'subscribed' implicitly has an 'any[]' type. (7008)
node_modules/angular2-localstorage/LocalStorageEmitter.ts (14,56): Property 'onTurnDone' does not exist on type 'NgZone'. (2339)
node_modules/angular2-localstorage/LocalStorageEmitter.ts (21,5): Member 'subscribers' implicitly has an 'any[]' type. (7008)`

Any chance on an update that fixes these items?

**Comment by jacerider** [comment]
Also getting this in LocalStorage.ts

`src/shared/localstorage/LocalStorage.ts (20,13): Variable 'instances' implicitly has an 'any[]' type. (7005)
src/shared/localstorage/LocalStorage.ts (41,21): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (42,21): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (46,24): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (53,21): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (54,21): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (62,17): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (71,36): Index signature of object type implicitly has an 'any' type. (7017)
src/shared/localstorage/LocalStorage.ts (73,21): Index signature of object type implicitly has an 'any' type. (7017)`

**Comment by marcj** [comment]
Did you try also current master version?

**Comment by jacerider** [comment]
This can be closed. I ended up going a different route. Thanks.
