### ISSUE TITLE
Instantiation error

### ISSUE THREAD

**Issue by no-more** [marcj/angular2-localStorage#13]
Hello,

I have the following error when I try to boot with angular2 beta 11

zone.ts?949c:855 
Unhandled Promise rejection: EXCEPTION: Error during instantiation of LocalStorageService!.
ORIGINAL EXCEPTION: TypeError: Cannot read property 'subscribe' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'subscribe' of undefined

I followed instruction and added LocalStorageSubscriber in the bootstrap process. I haven't added the decorator yet.

Thanks for your help.

**Comment by marcj** [comment]
Please try current master version. There has been a fixed pulled in https://github.com/marcj/angular2-localStorage/pull/8 for newer angular 2 version

**Comment by marcj** [comment]
Please try newest 0.3.0 version
