### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by SirDarquan** [marcj/angular2-localStorage#14]
This library is pretty slick. I thought I'd see how 'easy' it would be to add a sessionStorage decorator since technically it only requires 3 lines of code change. I was surprised that I couldn't just clone the project and begin changing stuff. You obviously have a build setup or the npm package wouldn't be possible. Would it be asking too much of you to share your build process or even make it part of the project so that contributing could be easier?

**Comment by marcj** [comment]
There is not build process involved. Once installed via npm you can just `require()` it like in the README explained. What issues do you have exactly?

**Comment by SirDarquan** [comment]
I'm sorry, when I said build I meant compile. The process of turning the Typescript files into JavaScript files.

**Comment by marcj** [comment]
Well, it's Angular2, this means they explained it pretty good at their website how to use Angular2 + Typescript. This library does not work if you use Angular2 + ECMAScript 5/6.

**Comment by SirDarquan** [comment]
This is true. I guess what I was hoping for was the package.json file would contain all the devDependencies needed to just make it work. For me to begin what I actually want to do I have to:
- clone your repository in to a folder
- npm install angular2
- npm install typings
- typings install es6-shim -A
- create a tsconfig.json and configure it to
  - use experimentalDecorators
  - use module commonjs
  - exclude files in the node_modules, and typings folders

All these steps are required before getting a successful compile to happen. Now, if you project already included the tsconfig.json file with the correct configuration and included angular2 and typings as devDependencies in the package.json and finally the created typings.json file was also included, then here's what I'd have to do to begin contributing:
- clone you repository into a folder
- npm install
  2 steps is also assuming that there is a post-install script that runs "typings install". 

I admit that if you're doing angular2 development, you probably know all of this, but why require everyone that wants to help to go through these steps if it could be as easy as doing an npm install?

**Comment by marcj** [comment]
Would be great to have such environment for development purposes. Would you mind creating another pull-reuest if you have already set it up by the last pull request? :)

**Comment by SirDarquan** [comment]
Sure. I'll have to clean it up a bit first though.
