### ISSUE TITLE
Instantiation Error / Angular2.0.0-beta.14

### ISSUE THREAD

**Issue by nick-jonas** [marcj/angular2-localStorage#17]
I'm getting this error:

```
Unhandled Promise rejection: EXCEPTION: Error during instantiation of LocalStorageService!.
ORIGINAL EXCEPTION: TypeError: Cannot read property 'subscribe' of undefined
```

My setup is just like on the README: 

```
import {LocalStorageSubscriber} from 'angular2-localstorage/LocalStorageEmitter'
let appPromise = bootstrap(App, [  .......providers.....])
LocalStorageSubscriber(appPromise)
```

Neither `appPromise` or `LocalStorageSubscriber` are undefined, I'm not sure how else to debug this?

![screen shot 2016-04-12 at 11 45 16 am](https://cloud.githubusercontent.com/assets/805682/14466313/38e863a8-00a4-11e6-8daa-112ba22de381.png)

**Comment by nick-jonas** [comment]
(I'm using v0.2.0)

**Comment by marcj** [comment]
This is fixed in master as well. Please try the master version

**Comment by nick-jonas** [comment]
Ah you're right, thank you - why isn't npm pulling from master?

**Comment by marcj** [comment]
I believe because the master hasn't a version tagged yet
