### ISSUE TITLE
Property 'onTurnDone' does not exist on type 'NgZone'.

### ISSUE THREAD

**Issue by nick-jonas** [marcj/angular2-localStorage#18]
Using 0.2.0 and Angular 2.0.0-beta.14, I'm getting this error out of Typescript transpiler:

```
client?bbee:44 ./~/angular2-localstorage/LocalStorageEmitter.ts
(14,56): error TS2339: Property 'onTurnDone' does not exist on type 'NgZone'.
```

**Comment by marcj** [comment]
This is fixed in master.

**Comment by final87** [comment]
can you give us the istruction to replace npm package with master ?
I get this error using master:
Error: Error: XHR error (404 Not Found) loading http://localhost:8087/node_modules/angular2-localstorage/LocalStorageEmitter.js
