### ISSUE TITLE
WebStorage.ts:72 Uncaught TypeError: Cannot read property '_username_mapped' of undefined

### ISSUE THREAD

**Issue by nick-jonas** [marcj/angular2-localStorage#19]
I'm getting this error when doing exactly what you have in the example of the README (the username example):

WebStorage.ts:72 Uncaught TypeError: Cannot read property '_username_mapped' of undefined

![screen shot 2016-04-12 at 12 39 14 pm](https://cloud.githubusercontent.com/assets/805682/14467962/b47a98ea-00ab-11e6-9160-3a8072214633.png)

**Comment by marcj** [comment]
Mh weird. Does this happen in all browsers for you? which versions do you exactly use?

**Comment by marcj** [comment]
Dub of #16
