### ISSUE TITLE
module '..../LocalStorageEmitter' has no exported member 'LocalStorageService'

### ISSUE THREAD

**Issue by fletchsod-developer** [marcj/angular2-localStorage#23]
Using the latest version, 0.2.0, I get this typescript error.    Using typescript version 1.8.10.

![image](https://cloud.githubusercontent.com/assets/5113337/14749821/a7d359ba-088f-11e6-8a9d-c58ecbd00ea1.png)

Upon looking in source code I found the "export" is missing.

![image](https://cloud.githubusercontent.com/assets/5113337/14749850/cc22e560-088f-11e6-8e1e-d87aa13d50f5.png)

By adding this "export" fixed the error.

![image](https://cloud.githubusercontent.com/assets/5113337/14749865/e29e80b0-088f-11e6-9cd3-3243e7487421.png)

**Comment by AlexCatch** [comment]
I can confirm this fixes the issue.

**Comment by marcj** [comment]
Oh, a typo. Would you like to create a pull-request guys?

**Comment by fletchsod-developer** [comment]
I never worked with GitHub development tools.  I guess somebody else can do.

**Comment by ghost** [comment]
I just wanted to submit a PR, but in the latest dev branch it has already been fixed.
https://github.com/marcj/angular2-localStorage/blob/master/LocalStorageEmitter.ts

When can we expect an updated NPM package?

**Comment by dragGH102** [comment]
same issue here (not just with latest beta).

**Comment by marcj** [comment]
Please try newest 0.3.0 version
