### ISSUE TITLE
Doesn't work in beta.16

### ISSUE THREAD

**Issue by maxisam** [marcj/angular2-localStorage#24]
I think it is because of this change https://github.com/angular/angular/commit/0a7d10ba55929b977f0aba2c1560a6644e9e323d

therefore, the following line doesn't work anymore.
`bla.injector.resolveAndInstantiate(<Type>LocalStorageService);`

**Comment by magnattic** [comment]
Same problem here, this currently prevents me from updating to the new angular2 version.

**Comment by roben** [comment]
I have created a pull request to the master branch which fixes the problem: https://github.com/marcj/angular2-localStorage/pull/26

**Comment by marcj** [comment]
Thanks!
