### ISSUE TITLE
cannot use with alpha4 angular2 webpack starter?

### ISSUE THREAD

**Issue by dvulanov** [marcj/angular2-localStorage#29]
Adding it to webpack vendor.ts: 

`import 'angular2-localstorage';`

I get this error:

```
[default] /Users/d/Documents/web_projects/angular2-webpack-starter/node_modules/angular2-localstorage/LocalStorageEmitter.ts:1:37 
    Cannot find module 'angular2/core'.
[default] /Users/d/Documents/web_projects/angular2-webpack-starter/node_modules/angular2-localstorage/LocalStorageEmitter.ts:2:22 
    Cannot find module 'angular2/src/core/zone'.
[default] /Users/d/Documents/web_projects/angular2-webpack-starter/node_modules/angular2-localstorage/LocalStorageEmitter.ts:46:20 
    Cannot find module 'angular2/src/facade/lang'.
[default] /Users/d/Documents/web_projects/angular2-webpack-starter/node_modules/angular2-localstorage/LocalStorageEmitter.ts:47:23 
    Cannot find module 'angular2/src/core/di'.
[default] /Users/d/Documents/web_projects/angular2-webpack-starter/node_modules/angular2-localstorage/LocalStorageEmitter.ts:48:28 
    Cannot find module 'angular2/core'.
```

Am I missing something, or does this package not support alpha4?  

Thanks for any help

**Comment by marcj** [comment]
alpha4 is a bit old, don't you think?

**Comment by dvulanov** [comment]
Sorry, by alpha4 I mean the latest from:

https://github.com/AngularClass/angular2-webpack-starter

which uses rc0.alpha4.

**Comment by marcj** [comment]
I believe they changed namespace to `@angular2/core` with a '@' prefix. This library has not updated yet to this new names.

**Comment by dvulanov** [comment]
I actually did try adding @ and still got the same error.  Unfortunately I'm not an expert on webpack and commonjs, so wasn't sure where to go after that.

**Comment by marcj** [comment]
I meant in the sourcecode of localStorage library, not in your sourcecode

**Comment by dvulanov** [comment]
Yes, that's what I meant, in your LocalStorageEmitter.ts ... but regardless, as you said, there's some updating needed to make it compatible with the current build.

I'll try again after next update.

Thanks!

**Comment by marcj** [comment]
Which angular version do you use exactly?

**Comment by dvulanov** [comment]
Sorry, it's actually angular2 2.0.0-rc.1   

(I erroneously referenced the 'alpha.4' from the also included angular2-material packages)

And again, I did a straight install from their repo:  https://github.com/AngularClass/angular2-webpack-starter

```
# clone our repo
# --depth 1 removes all but one .git commit history
git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git

# change directory to our repo
cd angular2-webpack-starter

# add required global libraries
npm install typings webpack-dev-server rimraf webpack -g

# install the repo with npm
npm install

# start the server
npm start
```

**Comment by marcj** [comment]
Please try newest 0.3.0 version with rc1 fixes
