### ISSUE TITLE
Compilation error on LocalStorageEmitter.ts(9,9)

### ISSUE THREAD

**Issue by micaelmbagira** [marcj/angular2-localStorage#3]
The compiler throws this error on LocalStorageEmitter line 9 : 
`error TS2342: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.`

It's about `LocalStorageEmitter.subscribed[ngZone]` because `ngZone` type is `NgZone`.

**Comment by marcj** [comment]
Thanks, there should be the id of ngZone used instead.

**Comment by micaelmbagira** [comment]
Does a `NgZone` object have an id ?

**Comment by marcj** [comment]
Good question, if not we need to generate our own id for it. I'm not sure yet

**Comment by Nolanus** [comment]
Interesting to read regarding this problem: http://stackoverflow.com/a/26269990/2225619
