### ISSUE TITLE
NPM keeps giving me a version 0.2.0 with incorrect files

### ISSUE THREAD

**Issue by ghost** [marcj/angular2-localStorage#32]
Npm keeps installing a version (0.2.0) with outdated files.
"LocalStorage.ts" instead of "WebStorage.ts"

<img width="218" alt="bildschirmfoto 2016-05-12 um 13 07 55" src="https://cloud.githubusercontent.com/assets/19324662/15212701/94069506-1842-11e6-9d3e-25cd1b975d33.png">

**Comment by final87** [comment]
I have the same issue, and using files downloaded directly from github give a lot of errors:

> http://localhost:8087/node_modules/angular2-localstorage/LocalStorageEmitter.js Failed to load resource: the server responded with a status of 404 (Not Found)
> 
> http://localhost:8087/node_modules/angular2-localstorage/WebStorage.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by timfogarty1549** [comment]
if you download the files directly from github, index.ts is still incorrect.  

bad:
export \* from './LocalStorage';
export \* from './LocalStorageEmitter';

correct:
export \* from './WebStorage';
export \* from './LocalStorageEmitter';

**Comment by final87** [comment]
index.js in Master seems correct:
export \* from './WebStorage';
export \* from './LocalStorageEmitter';

**Comment by marcj** [comment]
@final87 has been fixed yesterday

**Comment by marcj** [comment]
New version has been released in npm.

**Comment by final87** [comment]
`npm install angular2-localstorage` gives me:
Failed at the angular2-localstorage@0.3.0 postinstall script 'typings install'.
typings ERR! message Unknown dependency: registry:dt/es6-shim#0.31.2+20160317120654
