### ISSUE TITLE
Build errors with LocalStorageEmitter.ts

### ISSUE THREAD

**Issue by vinnybrown** [marcj/angular2-localStorage#5]
Getting a couple of build errors with beta 9:
1st error: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'. 
LocalStorageEmitter.subscribed[ngZone] = ngZone.onTurnDone.subscribe(() => {
            for (let callback of LocalStorageEmitter.subscribers) {
                callback();
            }
        });

It doesn't like the fact that you're using ngZone as an indexer.

2nd error: Generic type 'Promise<T>' requires 1 type argument
export function LocalStorageSubscriber(appPromise:Promise) {
    appPromise.then((bla) => {
        console.log('app booted', bla);
        console.log(bla.injector.resolveAndInstantiate(<Type>LocalStorageService));
    });
}

Here are the dependencies I have with my project:

"dependencies": {
    "ag-grid": "^4.0.0",
    "ag-grid-ng2": "^4.0.1",
    "angular2": "2.0.0-beta.9",
    "d3": "^3.5.16",
    "dragula": "^3.6.7",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.33.3",
    "es7-reflect-metadata": "1.6.0",
    "jquery": "^2.2.0",
    "loglevel": "^1.4.0",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15"
  },
"devDependencies": {
    "angular2-localstorage": "^0.1.0",
    "awesome-typescript-loader": "^0.16.0-rc.0",
    "bootstrap": "^4.0.0-alpha.2",
    "bootstrap-loader": "^1.0.7",
    "compression-webpack-plugin": "^0.3.0",
    "copy-webpack-plugin": "^1.0.0",
    "css-loader": "^0.23.0",
    "es6-promise-loader": "^1.0.1",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.8.5",
    "html-webpack-plugin": "^2.9.0",
    "http-server": "^0.8.5",
    "imports-loader": "^0.6.5",
    "istanbul-instrumenter-loader": "^0.2.0",
    "json-loader": "^0.5.4",
    "karma": "^0.13.21",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.3",
    "karma-jasmine": "^0.3.6",
    "karma-mocha-reporter": "^1.1.6",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-sourcemap-loader": "^0.3.6",
    "karma-webpack": "1.7.0",
    "ncp": "^2.0.0",
    "node-sass": "^3.4.1",
    "phantomjs": "^1.9.18",
    "phantomjs-polyfill": "0.0.1",
    "phantomjs-prebuilt": "^2.1.4",
    "protractor": "^3.1.1",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.2",
    "remap-istanbul": "^0.5.1",
    "replace": "^0.3.0",
    "resolve-url-loader": "^1.4.3",
    "sass-loader": "^3.1.1",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.0",
    "ts-helper": "0.0.1",
    "ts-node": "^0.5.5",
    "tsconfig-lint": "^0.6.0",
    "tslint": "^3.3.0",
    "tslint-loader": "^2.1.0",
    "typedoc": "^0.3.12",
    "typescript": "1.7.5",
    "typings": "^0.6.7",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.13",
    "webpack-dev-server": "^1.14.1",
    "webpack-load-plugins": "^0.1.2",
    "webpack-md5-hash": "^0.0.5"
  }

**Comment by lukeify** [comment]
+1 also getting this error.

**Comment by marcj** [comment]
This should be fixed by https://github.com/marcj/angular2-localStorage/pull/4
