### ISSUE TITLE
I can maintain the repo

### ISSUE THREAD

**Issue by PatrickJS** [marcj/angular2-localStorage#58]
I'm already doing something similar with HMR so I understand what's going on with it

**Comment by SET001** [comment]
Prove you can by making support for angular rc.5

**Comment by PatrickJS** [comment]
ping @marcj

**Comment by marcj** [comment]
@gdi2290 still interested?

**Comment by PatrickJS** [comment]
@marcj yup

**Comment by PatrickJS** [comment]
@marcj yo, I'm still interested

**Comment by phillipcurl** [comment]
@marcj please transfer to @gdi2290 His work is next-level and always incredibly reliable.
