### ISSUE TITLE
Getting initialization error

### ISSUE THREAD

**Issue by ultrasonicsoft** [marcj/angular2-localStorage#7]
Hi There,

I have added this package and while bootstrapping, I am getting below error:

angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <(…)ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434

My code:
import {bootstrap}    from 'angular2/platform/browser';
import {AppComponent} from './app.component';
import {LocalStorageSubscriber} from 'angular2-localstorage/LocalStorageEmitter';

var appPromise = bootstrap(AppComponent);

// register LocalStorage, this registers our change-detection.
LocalStorageSubscriber(appPromise);

I am using Angular 2.0 Beta 12 version of quick start code.
https://github.com/angular/quickstart/blob/master/README.md

Could you please do the needful?

Thanks!

**Comment by marcj** [comment]
Weird. Do you have a more complete stack trace? Looks like it's mainly inside the pilyfills. It doesn't show where its origin is.

**Comment by ultrasonicsoft** [comment]
That's the complete stack trace shown in browser's console.
Error is shown in angular2-polyfill.js.

When I was going through your code in Visual Studio Code, I saw there is compile time error in "LocalStorageEmitter.ts"

```
LocalStorageEmitter.subscribed[index] = ngZone.**onTurnDone**.subscribe(() => {
        for (let callback of LocalStorageEmitter.subscribers) {
            callback();
        }
    });
```

It says, *_Property 'onTurnDone' does not exist on type 'NgZone'.
*_

**Comment by marcj** [comment]
Well, then it seems Angular2 removed this event in the last released :( Do you know if there's a replacement?

**Comment by ultrasonicsoft** [comment]
I found the replacement:
https://github.com/angular/angular/search?utf8=%E2%9C%93&q=onTurnDone
NgZone.onTurnDone`=>`NgZone.onMicrotaskEmpty`

I changed this in local copy. I am able get rid of compile time error but runtime error is still same.

**Comment by ultrasonicsoft** [comment]
I think that issue is gone, but now i am getting different issue. It is unable to find LocalStorageEmitter while processing web app.

If you see in browser window, LocalStorageEmitter file has index.html content not the .js file content.

My code is as below:

import {bootstrap}    from 'angular2/platform/browser';
import {provide} from 'angular2/core';
import {ROUTER_PROVIDERS, APP_BASE_HREF, LocationStrategy, HashLocationStrategy} from 'angular2/router';

import {HomeComponent} from './home/home.component';
import {LocalStorageSubscriber} from 'angular2-localstorage/LocalStorageEmitter';

var appPromise = bootstrap(HomeComponent, [ROUTER_PROVIDERS]);
LocalStorageSubscriber(appPromise);

Can you think of any possible reason why it is not picking up LocalStorageEmitter.js file in browser?

![image](https://cloud.githubusercontent.com/assets/4145169/14050123/cdd26c52-f2df-11e5-9fec-e0491761ac5f.png)

**Comment by marcj** [comment]
Oh, good catch with onMicrotaskEmpty :)

`angular2-localstorage/LocalStorageEmitter` => `angular2-localStorage/LocalStorageEmitter` ? Looks like some load issues, nothing from localStorage directly.

**Comment by ultrasonicsoft** [comment]
agree!

Have you recently tested your package with latest angular2 beta 12 version? May I request if you have any working copy?
Thanks!

**Comment by ultrasonicsoft** [comment]
Okay dude, I have found the issue.

I have copied all .ts file locally and referred them. It's all working fine. That means, your npm package is having issue. You may need to fix your npm package. 

When I ran "npm install angular2-localStorage", it download package in node_module folder but in web deployment, that folder goes outside of node_module. Because of this, website can not find the package. (as you can see in my previous screen shot).

After coping those 2 files locally, it works like a charm! :)

**Comment by theunreal** [comment]
@ultrasonicsoft How did you referred them?

**Comment by ultrasonicsoft** [comment]
@theunreal I copied them locally and used import statement with local path.

**Comment by final87** [comment]
@ultrasonicsoft downloading Master repo and overwriting angular2-localstorage folder, i get this errore
Error: Error: XHR error (404 Not Found) loading http://localhost:8087/node_modules/angular2-localstorage/LocalStorageEmitter.js

can you help me?
do i have to overwite the npm package with the master files, or not? and I set ConfigJs to load the package but it doesn't find the .js file, which doesn't exist.

**Comment by ultrasonicsoft** [comment]
download only .ts files and put them in one of the new folder in your app folder structure. Then refer them using import. That's how I used in my case.

**Comment by final87** [comment]
doing that and fixing some typescript error, it then gives me this error:

> No provider for NgZone! 

I can added NgZone to the bootstrap but then it gives me 

> Cannot resolve all parameters for NgZone. Make sure they all have valid type or annotations

**Comment by marcj** [comment]
Meanwhile this library support only Angular1-RC1+ as angular introduced a lot of BC breaks.
