### ISSUE TITLE
Encryption for local storage

### ISSUE THREAD

**Issue by MounicaChette** [marcj/angular2-localStorage#9]
Is there any encryption included in this open source? Can I use secStore.js for encryption? But i suspect secStore.js is supported by javascript, not sure if this works for angular2-localStorage.

**Comment by marcj** [comment]
This library has no encryption on board. To be honest, I have never used secStore.js, so I don't know whether its compatible. If secStorage replaces window.localStorage then it might be compatible.

**Comment by MounicaChette** [comment]
Thanks for you reply marcj. I am using secStore.js file to encrypt and decrypt the local storage for now.
